### ISSUE TITLE
Add a blue screen of death!

### ISSUE THREAD

**Issue by WickedLynx** [Baddaboo/ClassicKit#1]

**Comment by Baddaboo** [comment]
Hmm, when would a BSOD make sense? Windows had a range of dialogs, from questions, errors, and critical errors to a flat BSOD (when something _really_ bad happened). Or it could just be call attached to `NotificationCenter`

**Comment by avioli** [comment]
It should be a view controller that's shown on top of the whole app, which hides the status bar even.

I imagine it should be like the `UIAlertController` - you instantiate it and then present it.

Probably create it it in `do {} catch { ... }` blocks for `try` calls.

**Comment by WickedLynx** [comment]
Yes, exactly what @avioli said! A view controller which 'hijacks' the app hiding navigation and the status bar and displays a configurable message.

**Comment by DominikBucher12** [comment]
For catching errors I believe bluescreen of death is proper solution.  👍

**Comment by Baddaboo** [comment]
So I wasn't sure what would trigger a BSOD in the browser, so I added one triggered by shaking the device. Check it out and let me know what you think!

**Comment by LeoNatan** [comment]
The font is fixedsys, and I am attaching it here. Not sure how it would look, as that font is meant to appear in 80×25 text mode. But give it a go.
[fixedsys.ttf.zip](https://github.com/Baddaboo/ClassicKit/files/2020588/fixedsys.ttf.zip)

**Comment by LeoNatan** [comment]
An idea is to have a BSOD manager as the uncaught exception handler 😂 and then, instead of crashing, run the runloop ad infinitum so it remains on screen.

**Comment by LeoNatan** [comment]
Running the runloop does not run or “burn” the CPU. Do you know what a runloop is?

**Comment by LeoNatan** [comment]
BTW, this is how it looks like with fixedsys. 
![ef595983-434a-4d08-b86b-f78d865bca87](https://user-images.githubusercontent.com/2270433/40283876-641363d2-5c8e-11e8-80f9-c72ec08ab6d6.png)

**Comment by Baddaboo** [comment]
@LeoNatan Thanks! I just pushed the font and adjusted the text for it. I think it looks great

**Comment by WickedLynx** [comment]
@Baddaboo This is PERFECT!!!! Awesome work :)
