### ISSUE TITLE
Incorrect font use, Windows 95 used MS San Serif

### ISSUE THREAD

**Issue by LeoNatan** [Baddaboo/ClassicKit#3]
Hello,

Cool library!
One minor remark—Windows 95 used MS Sans Serif rather than Tahoma.

Comparison of the two:
<img width="415" alt="screen shot 2018-05-16 at 13 06 29" src="https://user-images.githubusercontent.com/2270433/40110944-fd60d7dc-5909-11e8-9833-7f9718fe347b.png">

Attached here is the correct font.

[MS Sans Serif.ttf.zip](https://github.com/Baddaboo/ClassicKit/files/2008585/MS.Sans.Serif.ttf.zip)

**Comment by jtarchie** [comment]
I would tread lightly on the attached file. Fonts can have licensing issues. There may plenty of OSS sans-serif available, though. Google has one called [Open Sans](https://fonts.google.com/specimen/Open+Sans).

**Comment by LeoNatan** [comment]
@jtarchie Those are not raster fonts. Do you not see the difference between a vector font and a raster font, in the context of Windows 95?

Theoretically, the same license issue applies to Tahoma, which is already included and is still under license. MS Sans Serif (not Microsoft Sans Serif) is in the public domain if I recall correctly.

**Comment by Baddaboo** [comment]
@LeoNatan thanks! I had a hard time tracking down the original font.
@jtarchie I probably gave less thought to copyright than I should have. I sort of assumed that this is obviously a parody of Microsoft's design, that I'm not distributing commercially. I also figured that if they really did take issue with anything (like the Internet Explorer animation) I'd swap those elements with others. This is, after all, just a fun side project of mine 🙂

**Comment by LeoNatan** [comment]
Thanks!

**Comment by CapoFantasma97** [comment]
Where did you get it? Is there a bold version around?
