### ISSUE TITLE
Are the art assets original to this project?

### ISSUE THREAD

**Issue by colejd** [Baddaboo/ClassicKit#9]
Hello!

I'm about to publish an app I wrote with ClassicKit, but I need to cover my legal bases before I do so. Two questions:

- Is the navigation sound taken directly from Windows?
- Are the icons created specifically for this project (minus the Internet Explorer logo)? If not, where did they come from?

Thank you!

**Comment by Baddaboo** [comment]
Hi @colejd - I'll be honest, I've never directly dealt with the legal side of things publishing an app, but to answer your questions:
- Yes, the navigation sound was taken from Windows XP
- No, the icons were not created specifically for this project. They were taken from Windows 95 and converted to PNG files

**Comment by colejd** [comment]
That helps! Thank you. I'll see about producing some free variants of these resources, if you'd like them -- I'm not a very good artist though :p
